"""empty message

Revision ID: a34fed9b3b11
Revises: 
Create Date: 2022-04-26 15:39:22.066716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34fed9b3b11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('wins', sa.BigInteger(), nullable=True),
    sa.Column('losses', sa.BigInteger(), nullable=True),
    sa.Column('last_game', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_username'), 'leaderboard', ['username'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('leaderboard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leaderboard_id'], ['leaderboard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_leaderboard_username'), table_name='leaderboard')
    op.drop_table('leaderboard')
    # ### end Alembic commands ###
