version: "3.8"
services:
  # web:
  #   build: ./app
  #   command: gunicorn --bind 0.0.0.0:8000 -w 2 wsgi.app
  #   restart: always
  #   volumes:
  #     - ${PWD}:usr/src/app/
  #   ports:
  #     - "80:8000"
  #   depends_on:
  #     - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: blackjack_db
      PGUSER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}:/var/lib/data
